
Amenity.create(name: "wifi")
Amenity.create(name: "ensuite restroom")
Amenity.create(name: "shared restroom")
Amenity.create(name: "dry storage")
Amenity.create(name: "freezer storage")
Amenity.create(name: "cold storage")
Amenity.create(name: "commercial oven")
Amenity.create(name: "mixer")
Amenity.create(name: "poofer")
Amenity.create(name: "induction cooktop")
Amenity.create(name: "event space")
Amenity.create(name: "parking")
